name: Deploy Production

on:
    push:
        branches:
            - homolog
            - integrate-smoke-test
    workflow_dispatch:

jobs:
    deploy_production:
        runs-on: ubuntu-latest
        env:
            API_URL: "https://book-api-mlet.onrender.com"

        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Login Docker Hub
              uses: docker/login-action@v3
              with:
                username: ${{ secrets.DOCKERHUB_LOGIN }}
                password: ${{ secrets.DOCKERHUB_TOKEN }}

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3

            - name: Build and Push image
              uses: docker/build-push-action@v6
              with:
                push: true
                tags: ${{ secrets.DOCKERHUB_LOGIN }}/book_api:latest

            - name: Sync with Render
              run: |
                curl -X POST "https://api.render.com/v1/services/srv-d399ih8dl3ps73an6tkg/deploys" \
                -H "Authorization: Bearer ${{ secrets.RENDER_API_KEY }}" \
                -H "Content-Type: application/json"

            - name: Smoke Test
              run: python ./smoke_tests.main.py